### ISSUE TITLE
Flipping start_app/stop_app to not-invited concert

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#106] opened 2013-11-25 02:41 UTC
When two concerts are available in the network, if a robot get invited by one, it flips start_app and stop_app to both concerts.

For example,

"OPP concert" and "Concert tutorial" are visible in the network. A robot get invited by "OPP Concert". However, start_app and stop are visible on both "OPP Concert" and "Concert Tutorial"

**Comment by stonier** [comment] 2013-11-27 09:05
Reproduced:
- Start Robot
- Start OPP Concert
  - Robot got invited by OPP Concert
- Start Concert Tutorial on a different PC
  - Robot got invited by Concert Tutorial
- OPP Concert called start app
- Robot flipped to Concert Tutorial

**Comment by stonier** [comment] 2013-11-27 09:19
App managers weren't ignoring new invitations when already remote controlled.

**Comment by stonier** [comment] 2013-11-27 09:19
d9f7c396b3564a6efceeb88255861e91fd41e602 - block the invitation. Still spammy though, on robot and concert sides.

**Comment by stonier** [comment] 2013-11-27 09:21
Closing this here as it identified the root cause and fixed it, but following up on tedious issues in #217.

**Closed as completed by stonier** 2013-11-27 09:21 UTC
Labels: bug
